[project]
name = "6-arxiv-server"
version = "1.0.0"
description = "A simple MCP ArXiv server"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
