[project]
name = "6-math-server"
version = "1.0.0"
description = "A simple MCP math server"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
