[project]
name = "6-tavily-server"
version = "1.0.0"
description = "A simple MCP Tavily search server"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
